package kong

import (
	"net/http"
	"testing"

	"github.com/ParaServices/kong/object"
	"github.com/ParaServices/kong/plugin"
	"github.com/magicalbanana/tg"
	"github.com/stretchr/testify/require"
)

func TestClient_CreateJWTCredential(t *testing.T) {
	t.Run("create success", func(t *testing.T) {
		client, err := NewClient(kongURL(t))
		require.NoError(t, err)

		username, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		customID, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		consumer := object.NewConsumer(username, customID)
		createdConsumer, err := client.CreateConsumer(consumer)
		require.NoError(t, err)
		require.NotNil(t, createdConsumer)

		key, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		secret, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		jwtCred, err := plugin.NewJWTCredential(
			createdConsumer,
			plugin.SetJWTCredentialKey(key),
			plugin.SetJWTCredentialSecret(secret),
		)
		require.NoError(t, err)

		resp, err := client.CreateJWTCredential(jwtCred)
		require.NoError(t, err)
		require.NotNil(t, resp)
		// the ID that's returned is not the custom ID that was used to create
		// the JWT token but instead the ID generated by Kong
		require.Equal(t, createdConsumer.GetID(), resp.GetConsumer().GetID())
		require.NotEmpty(t, resp.ID)
	})
}

func TestClient_CreateJWTCredential_CustomerDoesNotExist(t *testing.T) {
	t.Run("consumer does not exist", func(t *testing.T) {
		client, err := NewClient(kongURL(t))
		require.NoError(t, err)

		jwtCred, err := plugin.NewJWTCredential(
			&object.Consumer{
				KongID: object.KongID{
					ID: "1",
				},
			},
			plugin.SetJWTCredentialKey("key"),
			plugin.SetJWTCredentialSecret("secret"),
		)
		require.NoError(t, err)

		resp, err := client.CreateJWTCredential(jwtCred)
		require.Error(t, err)
		errx := err.(KongError)
		require.Equal(t, http.StatusNotFound, errx.ResponseCode())
		require.Nil(t, resp)
	})
}

func TestClient_DeleteJWTCredential(t *testing.T) {
	t.Run("delete success", func(t *testing.T) {
		client, err := NewClient(kongURL(t))
		require.NoError(t, err)

		username, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		customID, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		consumer := object.NewConsumer(username, customID)
		createdConsumer, err := client.CreateConsumer(consumer)
		require.NoError(t, err)
		require.NotNil(t, createdConsumer)

		key, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		secret, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		jwtCred, err := plugin.NewJWTCredential(
			createdConsumer,
			plugin.SetJWTCredentialKey(key),
			plugin.SetJWTCredentialSecret(secret),
		)
		require.NoError(t, err)

		createdJWTCred, err := client.CreateJWTCredential(jwtCred)
		require.NoError(t, err)
		require.NotNil(t, createdJWTCred)
		require.Equal(t, createdConsumer.GetID(), createdJWTCred.GetConsumer().GetID())
		require.NotEmpty(t, createdJWTCred.ID)

		err = client.DeleteJWTCredential(createdJWTCred)
		require.NoError(t, err)
	})
}
