package kong

import (
	"net/http"
	"testing"

	"github.com/magicalbanana/tg"
	"github.com/stretchr/testify/require"
)

func TestClient_CreateJWTCredential(t *testing.T) {
	t.Run("create success", func(t *testing.T) {
		client := NewClient(1, 1, kongURL(t))

		usernameOrCustomID, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		r, err := client.CreateConsumer(usernameOrCustomID)
		require.NoError(t, err)
		require.NotNil(t, r)

		key, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		secret, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		resp, err := client.CreateJWTCredential(usernameOrCustomID, key, secret)
		require.NoError(t, err)
		require.NotNil(t, resp)
		// the ID that's returned is not the custom ID that was used to create
		// the JWT token but instead the ID generated by Kong
		require.Equal(t, r.ID, resp.Consumer.ID)
		require.NotEmpty(t, resp.ID)
	})
}

func TestClient_CreateJWTCredential_CustomerDoesNotExist(t *testing.T) {
	t.Run("consumer does not exist", func(t *testing.T) {
		client := NewClient(1, 1, kongURL(t))

		usernameOrCustomID, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		key, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		secret, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		resp, err := client.CreateJWTCredential(usernameOrCustomID, key, secret)
		require.Error(t, err)
		errx := err.(KongError)
		require.Equal(t, http.StatusNotFound, errx.ResponseCode())
		require.Nil(t, resp)
	})
}

func TestClient_DeleteJWTCredential(t *testing.T) {
	t.Run("delete success", func(t *testing.T) {
		client := NewClient(1, 1, kongURL(t))

		usernameOrCustomID, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		r, err := client.CreateConsumer(usernameOrCustomID)
		require.NoError(t, err)
		require.NotNil(t, r)

		key, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)
		secret, err := tg.RandGen(10, tg.Digit, "", "")
		require.NoError(t, err)

		resp, err := client.CreateJWTCredential(usernameOrCustomID, key, secret)
		require.NoError(t, err)
		require.NotNil(t, resp)
		require.Equal(t, r.ID, resp.Consumer.ID)
		require.NotEmpty(t, resp.ID)

		err = client.DeleteJWTCredential(usernameOrCustomID, resp.ID)
		require.NoError(t, err)
	})
}
